version: '3.7'
name: portfolio
volumes:
  sqlite_data:
  go_packages:
services:
  api:
    build: ../api
    working_dir: /app
    volumes:
      - go_packages:/go
      - sqlite_data:/var/lib/sqlite
      - ../api:/app
    env_file: api.env
    environment:
      CORS_ALLOW_ORIGINS: http://localhost:6061
      APP_LISTEN_PORT: 6060
      GO111MODULE: 'on'
      GOPATH: /go
      SQLITE_PATH: /var/lib/sqlite/auth.db
      TZ: Asia/Tokyo
    command: air -c .air.toml
    ports:
      - 6060:6060
    healthcheck:
      test: curl --fail -LI -XOPTIONS http://localhost:6060 || exit 1
      start_period: 3s
      interval: 10s
      timeout: 10s
      retries: 5
  web:
    image: node:19-alpine
    working_dir: /app
    volumes:
      - ../web:/app
    environment:
      NEXT_PUBLIC_CLIENT_SIDE_API_BASEPATH: http://localhost:6060
      SERVER_SIDE_API_BASEPATH: http://api:6060
      TZ: Asia/Tokyo
    command: yarn dev -p 6061
    ports:
      - 6061:6061
    depends_on:
      api:
        condition: service_healthy
